server:
  port: 8080
spring:
  application:
    name: '@project.artifactId@'
    version: '@project.version@'
  data:
    redis:
      host: "localhost"
      port: 6379
springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    use-root-path: true